extends: site.yaml
mode: production
context:
    data:
        menu:
            -
                name: Documentation
                description: 
                type: node
                url: documentation
            -
<<<<<<< HEAD
=======
                name: How it works
                description: 
                type: node
                url: how_it_works
            -
>>>>>>> new_hyde
                name: Tutorials
                description: 
                type: node
                url: tutorials
        sitetitle: Troia
        use_less_js: false
